runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1m"

handlers:
- url: /
  static_files: templates/home_fr.html
  upload: templates/home_fr.html
  secure: always

- url: /fr
  static_files: templates/home_fr.html
  upload: templates/home_fr.html
  secure: always

- url: /en
  static_files: templates/home_en.html
  upload: templates/home_en.html
  secure: always

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always
